In [1]:
import os
import numpy as np
import pandas as pd

In [2]:
# 設定路徑 data_path 
dir_data = 'C:/Users/USER/data/' #再創一個資料夾，複製路徑'\'改'/'，尾巴要再多加一個'/''

# 設定儲存資料的變數
f_app_train = os.path.join(dir_data, 'application_train.csv')
f_app_test = os.path.join(dir_data, 'application_test.csv')

#讀取資料
app_train = pd.read_csv(f_app_train)
app_test = pd.read_csv(f_app_test)

In [3]:
app_train

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.000,406597.5,24700.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.000,1293502.5,35698.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.000,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.000,312682.5,29686.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.000,513000.0,21865.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
5,100008,0,Cash loans,M,N,Y,0,99000.000,490495.5,27517.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
6,100009,0,Cash loans,F,Y,Y,1,171000.000,1560726.0,41301.0,...,0,0,0,0,0.0,0.0,0.0,1.0,1.0,2.0
7,100010,0,Cash loans,M,Y,Y,0,360000.000,1530000.0,42075.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
8,100011,0,Cash loans,F,N,Y,0,112500.000,1019610.0,33826.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
9,100012,0,Revolving loans,M,N,Y,0,135000.000,405000.0,20250.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
10,100014,0,Cash loans,F,N,Y,1,112500.000,652500.0,21177.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0
11,100015,0,Cash loans,F,N,Y,0,38419.155,148365.0,10678.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
12,100016,0,Cash loans,F,N,Y,0,67500.000,80865.0,5881.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0
13,100017,0,Cash loans,M,Y,N,1,225000.000,918468.0,28966.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
14,100018,0,Cash loans,F,N,Y,0,189000.000,773680.5,32778.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
15,100019,0,Cash loans,M,Y,Y,0,157500.000,299772.0,20160.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
16,100020,0,Cash loans,M,N,N,0,108000.000,509602.5,26149.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,0.0
17,100021,0,Revolving loans,F,N,Y,1,81000.000,270000.0,13500.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
18,100022,0,Revolving loans,F,N,Y,0,112500.000,157500.0,7875.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
19,100023,0,Cash loans,F,N,Y,1,90000.000,544491.0,17563.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
20,100024,0,Revolving loans,M,Y,Y,0,135000.000,427500.0,21375.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
21,100025,0,Cash loans,F,Y,Y,1,202500.000,1132573.5,37561.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,4.0
22,100026,0,Cash loans,F,N,N,1,450000.000,497520.0,32521.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,5.0
23,100027,0,Cash loans,F,N,Y,0,83250.000,239850.0,23850.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
24,100029,0,Cash loans,M,Y,N,2,135000.000,247500.0,12703.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
25,100030,0,Cash loans,F,N,Y,0,90000.000,225000.0,11074.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
26,100031,1,Cash loans,F,N,Y,0,112500.000,979992.0,27076.5,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,2.0
27,100032,0,Cash loans,M,N,Y,1,112500.000,327024.0,23827.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
28,100033,0,Cash loans,M,Y,Y,0,270000.000,790830.0,57676.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,1.0
29,100034,0,Revolving loans,M,N,Y,0,90000.000,180000.0,9000.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307481,456225,1,Cash loans,M,N,Y,0,225000.000,297000.0,19975.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
307482,456226,0,Cash loans,F,Y,Y,0,225000.000,500566.5,34969.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
307483,456227,0,Cash loans,F,N,Y,0,99000.000,247275.0,16479.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,5.0
307484,456228,0,Cash loans,F,Y,N,0,540000.000,545040.0,35617.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307485,456229,0,Revolving loans,F,N,Y,1,270000.000,180000.0,9000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
307486,456230,0,Cash loans,F,Y,Y,1,292500.000,355536.0,18283.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
307487,456231,0,Cash loans,M,N,Y,0,117000.000,1071909.0,31473.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,8.0
307488,456232,0,Cash loans,F,N,N,0,157500.000,135000.0,13351.5,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,1.0
307489,456233,1,Cash loans,F,N,Y,0,225000.000,521280.0,23089.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,2.0
307490,456234,0,Cash loans,M,N,Y,0,81000.000,135000.0,9148.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
307491,456235,0,Cash loans,M,Y,Y,2,90000.000,1078200.0,31522.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,7.0
307492,456236,0,Cash loans,M,Y,Y,0,585000.000,1575000.0,43443.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
307493,456237,0,Cash loans,F,N,Y,0,135000.000,946764.0,37678.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,7.0
307494,456238,0,Cash loans,M,Y,N,1,270000.000,479700.0,46858.5,...,0,0,0,0,0.0,0.0,1.0,0.0,0.0,1.0
307495,456239,0,Cash loans,M,Y,N,0,180000.000,808650.0,23773.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
307496,456240,0,Revolving loans,F,N,N,0,360000.000,337500.0,16875.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
307497,456241,0,Cash loans,F,Y,Y,0,180000.000,270126.0,12028.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,6.0
307498,456242,0,Cash loans,M,Y,Y,0,198000.000,1312110.0,52168.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
307499,456243,0,Cash loans,F,N,Y,0,81000.000,225000.0,12694.5,...,0,0,0,0,0.0,0.0,0.0,1.0,1.0,0.0
307500,456244,0,Cash loans,F,N,Y,0,261000.000,1303812.0,35982.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,5.0
307501,456245,0,Cash loans,F,N,Y,3,81000.000,269550.0,11871.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307502,456246,0,Cash loans,F,N,Y,1,94500.000,225000.0,10620.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
307503,456247,0,Cash loans,F,N,Y,0,112500.000,345510.0,17770.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,2.0
307504,456248,0,Cash loans,F,N,Y,0,153000.000,331920.0,16096.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307505,456249,0,Cash loans,F,N,Y,0,112500.000,225000.0,22050.0,...,0,0,0,0,0.0,0.0,0.0,2.0,0.0,0.0
307506,456251,0,Cash loans,M,N,N,0,157500.000,254700.0,27558.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307507,456252,0,Cash loans,F,N,Y,0,72000.000,269550.0,12001.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307508,456253,0,Cash loans,F,N,Y,0,153000.000,677664.0,29979.0,...,0,0,0,0,1.0,0.0,0.0,1.0,0.0,1.0
307509,456254,1,Cash loans,F,N,Y,0,171000.000,370107.0,20205.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
307510,456255,0,Cash loans,F,N,N,0,157500.000,675000.0,49117.5,...,0,0,0,0,0.0,0.0,0.0,2.0,0.0,1.0

In [5]:
#變數.dtypes.value_counts() 檢視資料中各個欄位類型的數量
#object文字 float64浮點數(小數) int64整數 
app_train.dtypes.value_counts()

float64    65
int64      41
object     16
dtype: int64

In [6]:
#變數.select_dtypes(include=["object"]).apply(pd.Series.nunique, axis = 0)
#檢視欄位型態為物件的資料，每個欄位有幾個變數
#e.g.'NAME_CONTRACT_TYPE'有'Cash loans'、'Revolving loans	'
app_train.select_dtypes(include=["object"]).apply(pd.Series.nunique, axis = 0)

NAME_CONTRACT_TYPE             2
CODE_GENDER                    3
FLAG_OWN_CAR                   2
FLAG_OWN_REALTY                2
NAME_TYPE_SUITE                7
NAME_INCOME_TYPE               8
NAME_EDUCATION_TYPE            5
NAME_FAMILY_STATUS             6
NAME_HOUSING_TYPE              6
OCCUPATION_TYPE               18
WEEKDAY_APPR_PROCESS_START     7
ORGANIZATION_TYPE             58
FONDKAPREMONT_MODE             4
HOUSETYPE_MODE                 3
WALLSMATERIAL_MODE             7
EMERGENCYSTATE_MODE            2
dtype: int64

Label encoding

In [7]:
from sklearn.preprocessing import LabelEncoder

In [8]:
# Create a label encoder object
le = LabelEncoder()
le_count = 0

# Iterate through the columns
for col in app_train:
    if app_train[col].dtype == 'object':
        # If 2 or fewer unique categories
        if len(list(app_train[col].unique())) <= 2:
            # Train on the training data
            le.fit(app_train[col])
            # Transform both training and testing data
            app_train[col] = le.transform(app_train[col])
            app_test[col] = le.transform(app_test[col])
            
            # Keep track of how many columns were label encoded
            le_count += 1
            
print('%d columns were label encoded.' % le_count)

3 columns were label encoded.

In [9]:
app_train #注意'NAME_CONTRACT_TYPE'欄位的改變

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,0,M,0,1,0,202500.000,406597.5,24700.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,0,F,0,0,0,270000.000,1293502.5,35698.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,1,M,1,1,0,67500.000,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,0,F,0,1,0,135000.000,312682.5,29686.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,0,M,0,1,0,121500.000,513000.0,21865.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
5,100008,0,0,M,0,1,0,99000.000,490495.5,27517.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
6,100009,0,0,F,1,1,1,171000.000,1560726.0,41301.0,...,0,0,0,0,0.0,0.0,0.0,1.0,1.0,2.0
7,100010,0,0,M,1,1,0,360000.000,1530000.0,42075.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
8,100011,0,0,F,0,1,0,112500.000,1019610.0,33826.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
9,100012,0,1,M,0,1,0,135000.000,405000.0,20250.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
10,100014,0,0,F,0,1,1,112500.000,652500.0,21177.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0
11,100015,0,0,F,0,1,0,38419.155,148365.0,10678.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
12,100016,0,0,F,0,1,0,67500.000,80865.0,5881.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0
13,100017,0,0,M,1,0,1,225000.000,918468.0,28966.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
14,100018,0,0,F,0,1,0,189000.000,773680.5,32778.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
15,100019,0,0,M,1,1,0,157500.000,299772.0,20160.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
16,100020,0,0,M,0,0,0,108000.000,509602.5,26149.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,0.0
17,100021,0,1,F,0,1,1,81000.000,270000.0,13500.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
18,100022,0,1,F,0,1,0,112500.000,157500.0,7875.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
19,100023,0,0,F,0,1,1,90000.000,544491.0,17563.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
20,100024,0,1,M,1,1,0,135000.000,427500.0,21375.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
21,100025,0,0,F,1,1,1,202500.000,1132573.5,37561.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,4.0
22,100026,0,0,F,0,0,1,450000.000,497520.0,32521.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,5.0
23,100027,0,0,F,0,1,0,83250.000,239850.0,23850.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
24,100029,0,0,M,1,0,2,135000.000,247500.0,12703.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
25,100030,0,0,F,0,1,0,90000.000,225000.0,11074.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
26,100031,1,0,F,0,1,0,112500.000,979992.0,27076.5,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,2.0
27,100032,0,0,M,0,1,1,112500.000,327024.0,23827.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
28,100033,0,0,M,1,1,0,270000.000,790830.0,57676.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,1.0
29,100034,0,1,M,0,1,0,90000.000,180000.0,9000.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307481,456225,1,0,M,0,1,0,225000.000,297000.0,19975.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
307482,456226,0,0,F,1,1,0,225000.000,500566.5,34969.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
307483,456227,0,0,F,0,1,0,99000.000,247275.0,16479.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,5.0
307484,456228,0,0,F,1,0,0,540000.000,545040.0,35617.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307485,456229,0,1,F,0,1,1,270000.000,180000.0,9000.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
307486,456230,0,0,F,1,1,1,292500.000,355536.0,18283.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
307487,456231,0,0,M,0,1,0,117000.000,1071909.0,31473.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,8.0
307488,456232,0,0,F,0,0,0,157500.000,135000.0,13351.5,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,1.0
307489,456233,1,0,F,0,1,0,225000.000,521280.0,23089.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,2.0
307490,456234,0,0,M,0,1,0,81000.000,135000.0,9148.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
307491,456235,0,0,M,1,1,2,90000.000,1078200.0,31522.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,7.0
307492,456236,0,0,M,1,1,0,585000.000,1575000.0,43443.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
307493,456237,0,0,F,0,1,0,135000.000,946764.0,37678.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,7.0
307494,456238,0,0,M,1,0,1,270000.000,479700.0,46858.5,...,0,0,0,0,0.0,0.0,1.0,0.0,0.0,1.0
307495,456239,0,0,M,1,0,0,180000.000,808650.0,23773.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
307496,456240,0,1,F,0,0,0,360000.000,337500.0,16875.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
307497,456241,0,0,F,1,1,0,180000.000,270126.0,12028.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,6.0
307498,456242,0,0,M,1,1,0,198000.000,1312110.0,52168.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
307499,456243,0,0,F,0,1,0,81000.000,225000.0,12694.5,...,0,0,0,0,0.0,0.0,0.0,1.0,1.0,0.0
307500,456244,0,0,F,0,1,0,261000.000,1303812.0,35982.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,5.0
307501,456245,0,0,F,0,1,3,81000.000,269550.0,11871.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307502,456246,0,0,F,0,1,1,94500.000,225000.0,10620.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
307503,456247,0,0,F,0,1,0,112500.000,345510.0,17770.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,2.0
307504,456248,0,0,F,0,1,0,153000.000,331920.0,16096.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307505,456249,0,0,F,0,1,0,112500.000,225000.0,22050.0,...,0,0,0,0,0.0,0.0,0.0,2.0,0.0,0.0
307506,456251,0,0,M,0,0,0,157500.000,254700.0,27558.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307507,456252,0,0,F,0,1,0,72000.000,269550.0,12001.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
307508,456253,0,0,F,0,1,0,153000.000,677664.0,29979.0,...,0,0,0,0,1.0,0.0,0.0,1.0,0.0,1.0
307509,456254,1,0,F,0,1,0,171000.000,370107.0,20205.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
307510,456255,0,0,F,0,0,0,157500.000,675000.0,49117.5,...,0,0,0,0,0.0,0.0,0.0,2.0,0.0,1.0

One Hot encoding

In [10]:
app_train = pd.get_dummies(app_train)
app_test = pd.get_dummies(app_test)

In [11]:
app_train

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,...,HOUSETYPE_MODE_terraced house,WALLSMATERIAL_MODE_Block,WALLSMATERIAL_MODE_Mixed,WALLSMATERIAL_MODE_Monolithic,WALLSMATERIAL_MODE_Others,WALLSMATERIAL_MODE_Panel,"WALLSMATERIAL_MODE_Stone, brick",WALLSMATERIAL_MODE_Wooden,EMERGENCYSTATE_MODE_No,EMERGENCYSTATE_MODE_Yes
0,100002,1,0,0,1,0,202500.000,406597.5,24700.5,351000.0,...,0,0,0,0,0,0,1,0,1,0
1,100003,0,0,0,0,0,270000.000,1293502.5,35698.5,1129500.0,...,0,1,0,0,0,0,0,0,1,0
2,100004,0,1,1,1,0,67500.000,135000.0,6750.0,135000.0,...,0,0,0,0,0,0,0,0,0,0
3,100006,0,0,0,1,0,135000.000,312682.5,29686.5,297000.0,...,0,0,0,0,0,0,0,0,0,0
4,100007,0,0,0,1,0,121500.000,513000.0,21865.5,513000.0,...,0,0,0,0,0,0,0,0,0,0
5,100008,0,0,0,1,0,99000.000,490495.5,27517.5,454500.0,...,0,0,0,0,0,0,0,0,0,0
6,100009,0,0,1,1,1,171000.000,1560726.0,41301.0,1395000.0,...,0,0,0,0,0,0,0,0,0,0
7,100010,0,0,1,1,0,360000.000,1530000.0,42075.0,1530000.0,...,0,0,0,0,0,0,0,0,0,0
8,100011,0,0,0,1,0,112500.000,1019610.0,33826.5,913500.0,...,0,0,0,0,0,0,0,0,0,0
9,100012,0,1,0,1,0,135000.000,405000.0,20250.0,405000.0,...,0,0,0,0,0,0,0,0,0,0
10,100014,0,0,0,1,1,112500.000,652500.0,21177.0,652500.0,...,0,0,0,0,0,0,0,0,0,0
11,100015,0,0,0,1,0,38419.155,148365.0,10678.5,135000.0,...,0,0,0,0,0,0,0,0,0,0
12,100016,0,0,0,1,0,67500.000,80865.0,5881.5,67500.0,...,0,0,0,0,0,0,0,0,1,0
13,100017,0,0,1,0,1,225000.000,918468.0,28966.5,697500.0,...,0,0,0,0,0,1,0,0,1,0
14,100018,0,0,0,1,0,189000.000,773680.5,32778.0,679500.0,...,0,0,0,0,0,1,0,0,1,0
15,100019,0,0,1,1,0,157500.000,299772.0,20160.0,247500.0,...,0,0,0,0,0,0,0,0,0,0
16,100020,0,0,0,0,0,108000.000,509602.5,26149.5,387000.0,...,0,0,0,0,0,0,0,0,0,0
17,100021,0,1,0,1,1,81000.000,270000.0,13500.0,270000.0,...,0,0,0,0,0,0,0,0,0,0
18,100022,0,1,0,1,0,112500.000,157500.0,7875.0,157500.0,...,0,0,0,0,0,0,1,0,1,0
19,100023,0,0,0,1,1,90000.000,544491.0,17563.5,454500.0,...,0,0,0,0,0,0,0,0,0,0
20,100024,0,1,1,1,0,135000.000,427500.0,21375.0,427500.0,...,0,0,0,0,0,0,1,0,1,0
21,100025,0,0,1,1,1,202500.000,1132573.5,37561.5,927000.0,...,0,0,0,0,0,0,0,0,0,0
22,100026,0,0,0,0,1,450000.000,497520.0,32521.5,450000.0,...,0,0,0,0,0,1,0,0,1,0
23,100027,0,0,0,1,0,83250.000,239850.0,23850.0,225000.0,...,0,0,1,0,0,0,0,0,1,0
24,100029,0,0,1,0,2,135000.000,247500.0,12703.5,247500.0,...,0,0,0,0,0,1,0,0,1,0
25,100030,0,0,0,1,0,90000.000,225000.0,11074.5,225000.0,...,0,0,0,0,0,0,1,0,1,0
26,100031,1,0,0,1,0,112500.000,979992.0,27076.5,702000.0,...,0,0,0,0,0,0,0,1,0,1
27,100032,0,0,0,1,1,112500.000,327024.0,23827.5,270000.0,...,0,0,0,0,0,0,0,0,0,0
28,100033,0,0,1,1,0,270000.000,790830.0,57676.5,675000.0,...,0,0,0,0,0,0,0,0,0,0
29,100034,0,1,0,1,0,90000.000,180000.0,9000.0,180000.0,...,0,0,0,0,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307481,456225,1,0,0,1,0,225000.000,297000.0,19975.5,297000.0,...,0,0,0,0,0,0,0,0,0,0
307482,456226,0,0,1,1,0,225000.000,500566.5,34969.5,472500.0,...,0,1,0,0,0,0,0,0,1,0
307483,456227,0,0,0,1,0,99000.000,247275.0,16479.0,225000.0,...,0,0,0,0,0,0,1,0,1,0
307484,456228,0,0,1,0,0,540000.000,545040.0,35617.5,450000.0,...,0,0,0,0,0,0,0,0,0,0
307485,456229,0,1,0,1,1,270000.000,180000.0,9000.0,180000.0,...,0,0,0,0,0,0,0,0,0,0
307486,456230,0,0,1,1,1,292500.000,355536.0,18283.5,270000.0,...,0,0,0,0,0,1,0,0,1,0
307487,456231,0,0,0,1,0,117000.000,1071909.0,31473.0,936000.0,...,0,0,0,0,0,0,0,0,0,0
307488,456232,0,0,0,0,0,157500.000,135000.0,13351.5,135000.0,...,0,0,0,0,0,0,0,0,1,0
307489,456233,1,0,0,1,0,225000.000,521280.0,23089.5,450000.0,...,0,0,0,0,0,0,1,0,0,1
307490,456234,0,0,0,1,0,81000.000,135000.0,9148.5,135000.0,...,0,0,0,0,0,0,0,0,0,0
307491,456235,0,0,1,1,2,90000.000,1078200.0,31522.5,900000.0,...,0,0,0,0,0,0,0,0,0,0
307492,456236,0,0,1,1,0,585000.000,1575000.0,43443.0,1575000.0,...,0,0,0,0,0,0,0,0,0,0
307493,456237,0,0,0,1,0,135000.000,946764.0,37678.5,765000.0,...,0,0,0,0,0,0,0,0,0,0
307494,456238,0,0,1,0,1,270000.000,479700.0,46858.5,450000.0,...,0,0,0,0,0,0,0,0,0,0
307495,456239,0,0,1,0,0,180000.000,808650.0,23773.5,675000.0,...,0,0,0,0,0,1,0,0,1,0
307496,456240,0,1,0,0,0,360000.000,337500.0,16875.0,337500.0,...,0,0,0,0,0,0,0,0,0,0
307497,456241,0,0,1,1,0,180000.000,270126.0,12028.5,193500.0,...,0,0,0,0,0,0,0,0,0,0
307498,456242,0,0,1,1,0,198000.000,1312110.0,52168.5,1125000.0,...,0,0,0,0,0,1,0,0,1,0
307499,456243,0,0,0,1,0,81000.000,225000.0,12694.5,225000.0,...,0,0,0,0,0,0,0,0,0,0
307500,456244,0,0,0,1,0,261000.000,1303812.0,35982.0,1138500.0,...,0,0,0,0,0,1,0,0,1,0
307501,456245,0,0,0,1,3,81000.000,269550.0,11871.0,225000.0,...,0,0,0,0,0,0,1,0,1,0
307502,456246,0,0,0,1,1,94500.000,225000.0,10620.0,225000.0,...,0,0,0,0,0,0,0,0,0,0
307503,456247,0,0,0,1,0,112500.000,345510.0,17770.5,247500.0,...,0,0,0,0,0,0,0,0,0,0
307504,456248,0,0,0,1,0,153000.000,331920.0,16096.5,225000.0,...,0,0,0,0,0,0,0,0,0,0
307505,456249,0,0,0,1,0,112500.000,225000.0,22050.0,225000.0,...,0,0,0,0,0,1,0,0,1,0
307506,456251,0,0,0,0,0,157500.000,254700.0,27558.0,225000.0,...,0,0,0,0,0,0,1,0,1,0
307507,456252,0,0,0,1,0,72000.000,269550.0,12001.5,225000.0,...,0,0,0,0,0,0,1,0,1,0
307508,456253,0,0,0,1,0,153000.000,677664.0,29979.0,585000.0,...,0,0,0,0,0,1,0,0,1,0
307509,456254,1,0,0,1,0,171000.000,370107.0,20205.0,319500.0,...,0,0,0,0,0,0,1,0,1,0
307510,456255,0,0,0,0,0,157500.000,675000.0,49117.5,675000.0,...,0,0,0,0,0,1,0,0,1,0

In [12]:
app_train.info

<bound method DataFrame.info of         SK_ID_CURR  TARGET  NAME_CONTRACT_TYPE  FLAG_OWN_CAR  FLAG_OWN_REALTY  \
0           100002       1                   0             0                1
1           100003       0                   0             0                0
2           100004       0                   1             1                1
3           100006       0                   0             0                1
4           100007       0                   0             0                1
5           100008       0                   0             0                1
6           100009       0                   0             1                1
7           100010       0                   0             1                1
8           100011       0                   0             0                1
9           100012       0                   1             0                1
10          100014       0                   0             0                1
11          100015       0                   0             0                1
12          100016       0                   0             0                1
13          100017       0                   0             1                0
14          100018       0                   0             0                1
15          100019       0                   0             1                1
16          100020       0                   0             0                0
17          100021       0                   1             0                1
18          100022       0                   1             0                1
19          100023       0                   0             0                1
20          100024       0                   1             1                1
21          100025       0                   0             1                1
22          100026       0                   0             0                0
23          100027       0                   0             0                1
24          100029       0                   0             1                0
25          100030       0                   0             0                1
26          100031       1                   0             0                1
27          100032       0                   0             0                1
28          100033       0                   0             1                1
29          100034       0                   1             0                1
...            ...     ...                 ...           ...              ...
307481      456225       1                   0             0                1
307482      456226       0                   0             1                1
307483      456227       0                   0             0                1
307484      456228       0                   0             1                0
307485      456229       0                   1             0                1
307486      456230       0                   0             1                1
307487      456231       0                   0             0                1
307488      456232       0                   0             0                0
307489      456233       1                   0             0                1
307490      456234       0                   0             0                1
307491      456235       0                   0             1                1
307492      456236       0                   0             1                1
307493      456237       0                   0             0                1
307494      456238       0                   0             1                0
307495      456239       0                   0             1                0
307496      456240       0                   1             0                0
307497      456241       0                   0             1                1
307498      456242       0                   0             1                1
307499      456243       0                   0             0                1
307500      456244       0                   0             0                1
307501      456245       0                   0             0                1
307502      456246       0                   0             0                1
307503      456247       0                   0             0                1
307504      456248       0                   0             0                1
307505      456249       0                   0             0                1
307506      456251       0                   0             0                0
307507      456252       0                   0             0                1
307508      456253       0                   0             0                1
307509      456254       1                   0             0                1
307510      456255       0                   0             0                0

        CNT_CHILDREN  AMT_INCOME_TOTAL  AMT_CREDIT  AMT_ANNUITY  \
0                  0        202500.000    406597.5      24700.5
1                  0        270000.000   1293502.5      35698.5
2                  0         67500.000    135000.0       6750.0
3                  0        135000.000    312682.5      29686.5
4                  0        121500.000    513000.0      21865.5
5                  0         99000.000    490495.5      27517.5
6                  1        171000.000   1560726.0      41301.0
7                  0        360000.000   1530000.0      42075.0
8                  0        112500.000   1019610.0      33826.5
9                  0        135000.000    405000.0      20250.0
10                 1        112500.000    652500.0      21177.0
11                 0         38419.155    148365.0      10678.5
12                 0         67500.000     80865.0       5881.5
13                 1        225000.000    918468.0      28966.5
14                 0        189000.000    773680.5      32778.0
15                 0        157500.000    299772.0      20160.0
16                 0        108000.000    509602.5      26149.5
17                 1         81000.000    270000.0      13500.0
18                 0        112500.000    157500.0       7875.0
19                 1         90000.000    544491.0      17563.5
20                 0        135000.000    427500.0      21375.0
21                 1        202500.000   1132573.5      37561.5
22                 1        450000.000    497520.0      32521.5
23                 0         83250.000    239850.0      23850.0
24                 2        135000.000    247500.0      12703.5
25                 0         90000.000    225000.0      11074.5
26                 0        112500.000    979992.0      27076.5
27                 1        112500.000    327024.0      23827.5
28                 0        270000.000    790830.0      57676.5
29                 0         90000.000    180000.0       9000.0
...              ...               ...         ...          ...
307481             0        225000.000    297000.0      19975.5
307482             0        225000.000    500566.5      34969.5
307483             0         99000.000    247275.0      16479.0
307484             0        540000.000    545040.0      35617.5
307485             1        270000.000    180000.0       9000.0
307486             1        292500.000    355536.0      18283.5
307487             0        117000.000   1071909.0      31473.0
307488             0        157500.000    135000.0      13351.5
307489             0        225000.000    521280.0      23089.5
307490             0         81000.000    135000.0       9148.5
307491             2         90000.000   1078200.0      31522.5
307492             0        585000.000   1575000.0      43443.0
307493             0        135000.000    946764.0      37678.5
307494             1        270000.000    479700.0      46858.5
307495             0        180000.000    808650.0      23773.5
307496             0        360000.000    337500.0      16875.0
307497             0        180000.000    270126.0      12028.5
307498             0        198000.000   1312110.0      52168.5
307499             0         81000.000    225000.0      12694.5
307500             0        261000.000   1303812.0      35982.0
307501             3         81000.000    269550.0      11871.0
307502             1         94500.000    225000.0      10620.0
307503             0        112500.000    345510.0      17770.5
307504             0        153000.000    331920.0      16096.5
307505             0        112500.000    225000.0      22050.0
307506             0        157500.000    254700.0      27558.0
307507             0         72000.000    269550.0      12001.5
307508             0        153000.000    677664.0      29979.0
307509             0        171000.000    370107.0      20205.0
307510             0        157500.000    675000.0      49117.5

        AMT_GOODS_PRICE           ...             \
0              351000.0           ...
1             1129500.0           ...
2              135000.0           ...
3              297000.0           ...
4              513000.0           ...
5              454500.0           ...
6             1395000.0           ...
7             1530000.0           ...
8              913500.0           ...
9              405000.0           ...
10             652500.0           ...
11             135000.0           ...
12              67500.0           ...
13             697500.0           ...
14             679500.0           ...
15             247500.0           ...
16             387000.0           ...
17             270000.0           ...
18             157500.0           ...
19             454500.0           ...
20             427500.0           ...
21             927000.0           ...
22             450000.0           ...
23             225000.0           ...
24             247500.0           ...
25             225000.0           ...
26             702000.0           ...
27             270000.0           ...
28             675000.0           ...
29             180000.0           ...
...                 ...           ...
307481         297000.0           ...
307482         472500.0           ...
307483         225000.0           ...
307484         450000.0           ...
307485         180000.0           ...
307486         270000.0           ...
307487         936000.0           ...
307488         135000.0           ...
307489         450000.0           ...
307490         135000.0           ...
307491         900000.0           ...
307492        1575000.0           ...
307493         765000.0           ...
307494         450000.0           ...
307495         675000.0           ...
307496         337500.0           ...
307497         193500.0           ...
307498        1125000.0           ...
307499         225000.0           ...
307500        1138500.0           ...
307501         225000.0           ...
307502         225000.0           ...
307503         247500.0           ...
307504         225000.0           ...
307505         225000.0           ...
307506         225000.0           ...
307507         225000.0           ...
307508         585000.0           ...
307509         319500.0           ...
307510         675000.0           ...

        HOUSETYPE_MODE_terraced house  WALLSMATERIAL_MODE_Block  \
0                                   0                         0
1                                   0                         1
2                                   0                         0
3                                   0                         0
4                                   0                         0
5                                   0                         0
6                                   0                         0
7                                   0                         0
8                                   0                         0
9                                   0                         0
10                                  0                         0
11                                  0                         0
12                                  0                         0
13                                  0                         0
14                                  0                         0
15                                  0                         0
16                                  0                         0
17                                  0                         0
18                                  0                         0
19                                  0                         0
20                                  0                         0
21                                  0                         0
22                                  0                         0
23                                  0                         0
24                                  0                         0
25                                  0                         0
26                                  0                         0
27                                  0                         0
28                                  0                         0
29                                  0                         0
...                               ...                       ...
307481                              0                         0
307482                              0                         1
307483                              0                         0
307484                              0                         0
307485                              0                         0
307486                              0                         0
307487                              0                         0
307488                              0                         0
307489                              0                         0
307490                              0                         0
307491                              0                         0
307492                              0                         0
307493                              0                         0
307494                              0                         0
307495                              0                         0
307496                              0                         0
307497                              0                         0
307498                              0                         0
307499                              0                         0
307500                              0                         0
307501                              0                         0
307502                              0                         0
307503                              0                         0
307504                              0                         0
307505                              0                         0
307506                              0                         0
307507                              0                         0
307508                              0                         0
307509                              0                         0
307510                              0                         0

        WALLSMATERIAL_MODE_Mixed  WALLSMATERIAL_MODE_Monolithic  \
0                              0                              0
1                              0                              0
2                              0                              0
3                              0                              0
4                              0                              0
5                              0                              0
6                              0                              0
7                              0                              0
8                              0                              0
9                              0                              0
10                             0                              0
11                             0                              0
12                             0                              0
13                             0                              0
14                             0                              0
15                             0                              0
16                             0                              0
17                             0                              0
18                             0                              0
19                             0                              0
20                             0                              0
21                             0                              0
22                             0                              0
23                             1                              0
24                             0                              0
25                             0                              0
26                             0                              0
27                             0                              0
28                             0                              0
29                             0                              0
...                          ...                            ...
307481                         0                              0
307482                         0                              0
307483                         0                              0
307484                         0                              0
307485                         0                              0
307486                         0                              0
307487                         0                              0
307488                         0                              0
307489                         0                              0
307490                         0                              0
307491                         0                              0
307492                         0                              0
307493                         0                              0
307494                         0                              0
307495                         0                              0
307496                         0                              0
307497                         0                              0
307498                         0                              0
307499                         0                              0
307500                         0                              0
307501                         0                              0
307502                         0                              0
307503                         0                              0
307504                         0                              0
307505                         0                              0
307506                         0                              0
307507                         0                              0
307508                         0                              0
307509                         0                              0
307510                         0                              0

        WALLSMATERIAL_MODE_Others  WALLSMATERIAL_MODE_Panel  \
0                               0                         0
1                               0                         0
2                               0                         0
3                               0                         0
4                               0                         0
5                               0                         0
6                               0                         0
7                               0                         0
8                               0                         0
9                               0                         0
10                              0                         0
11                              0                         0

In [13]:
print(app_train['CODE_GENDER_F'].head())
print(app_train['CODE_GENDER_M'].head())
print(app_train['NAME_EDUCATION_TYPE_Academic degree'].head())

0    0
1    1
2    0
3    1
4    0
Name: CODE_GENDER_F, dtype: uint8
0    1
1    0
2    1
3    0
4    1
Name: CODE_GENDER_M, dtype: uint8
0    0
1    0
2    0
3    0
4    0
Name: NAME_EDUCATION_TYPE_Academic degree, dtype: uint8